version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # This volume mounts the current directory into the container's /app directory
      - .:/app
      # Ensure node_modules are not overwritten by the local environment
      - /app/node_modules
      - ~/.ssh:/root/.ssh
    environment:
      - NODE_ENV=development
    command: npm run start
